###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "rishabh",
    "email" : "yrishabh325@gmail.com",
    "phone" : "1122334455",
    "password" : "rishabh123"
}



###
GET http://localhost:5000/api/auth/verifyEmail?token=42bb38ffbe4d9b45ecd457a5a4db1d9dc2d5722fa5f5dc2a6b377a4f56290a07



###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email" : "yrishabh325@gmail.com",
    "password" : "rishabh123"
}

###

POST http://localhost:5000/api/form/contact
Content-Type: application/json

{
    "username":"rishabh",
    "email" : "yrishabh325@gmail.com",
    "message" : "testing mern 2025"
}





